name : Build and Deploy API to Azure portal

# This workflow will build and deploy the API to Azure portal when there is a push to the main branch.
on:
  push:
    branches:
      - main

# Job is a collection of steps that run in an environment.
# In simple word , job is a workflow of the pipeline.
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        
        steps:
            # Checkout code from the repository to the ubuntu-latest environment.
            - name: Checkout code
              id: github-checkout
              uses: actions/checkout@v3

            # Set up .NET environment to build the API on ubuntu-latest environment.
            - name: Set up Web api core .NET
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '8.0.x'

            # Connecting to Azure Container Registry (ACR) to push the docker image of the API to ACR.
            - name: Configure Azure Container Registry (ACR) credentials
              uses: azure/docker-login@v2
              with:
                login-server: ${{ vars.AZURE_CONTAINER_REGISTRY_SERVER_URI }}
                username: ${{ secrets.ACR_USERNAME }}
                password: ${{ secrets.ACR_PASSWORD }}

