name: Build and Deploy API to Azure portal

# This workflow will build and deploy the API to Azure portal when there is a push to the main branch.
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the repository
      - name: Checkout code
        id: github-checkout
        uses: actions/checkout@v4

      # Set up .NET environment to build the API
      - name: Set up Web api core .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Log in to Azure Container Registry (ACR)
      - name: Configure Azure Container Registry (ACR) credentials
        uses: azure/docker-login@v2
        with:
          login-server: ${{ vars.AZURE_CONTAINER_REGISTRY_SERVER_URI }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Get short commit SHA for image tagging
      - name: SHA of the commit
        id: vars
        run: |
            calculatedSha=$(git rev-parse --short ${{ github.sha }})
            echo "::set-output name=short_sha::$calculatedSha"

     # Build and push the Docker image to Azure Container Registry (ACR)
      - name: Build and push Docker image to ACR
        env:
            ACR_REGISTRY: ${{ vars.AZURE_CONTAINER_REGISTRY_SERVER_URI }}
            IMAGE_TAG: ${{ steps.vars.outputs.short_sha }}
        run: |
            docker build -f FormulaOne.Dockerfile -t $ACR_REGISTRY/f1app:$IMAGE_TAG -t $ACR_REGISTRY/f1app:latest .
            docker push $ACR_REGISTRY/f1app --all-tags
      

    