name: Build and Deploy API to Azure portal

# This workflow will build and deploy the API to Azure portal when there is a push to the main branch.
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.vars.outputs.short_sha }}

    steps:
      # Checkout code from the repository
      - name: Checkout code
        id: github-checkout
        uses: actions/checkout@v4

      # Set up .NET environment to build the API
      - name: Set up Web api core .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Log in to Azure Container Registry (ACR)
      - name: Configure Azure Container Registry (ACR) credentials
        uses: azure/docker-login@v2
        with:
          login-server: ${{ vars.AZURE_CONTAINER_REGISTRY_SERVER_URI }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Get short commit SHA for image tagging
      - name: SHA of the commit
        id: vars
        run: |
            calculatedSha=$(git rev-parse --short ${{ github.sha }})
            echo "::set-output name=short_sha::$calculatedSha"

     # Build and push the Docker image to Azure Container Registry (ACR)
      - name: Build and push Docker image to ACR
        env:
            ACR_REGISTRY: ${{ vars.AZURE_CONTAINER_REGISTRY_SERVER_URI }}
            IMAGE_TAG: ${{ steps.vars.outputs.short_sha }}
        run: |
            docker build -f FormulaOne.Dockerfile -t $ACR_REGISTRY/f1app:$IMAGE_TAG -t $ACR_REGISTRY/f1app:latest .
            docker push $ACR_REGISTRY/f1app --all-tags
      

  deploy-container-to-ACS:
    runs-on: ubuntu-latest
    needs: build-and-deploy

    steps:
      # Log in to Azure CLI
      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy the Docker image to Azure Container Service (ACS)
      - name: Deploy Docker image to ACS
        uses: azure/login@v1

        with:
            # generate by running `az ad sp create-for-rbac --name github-auth --role Contributor --scopes /subscriptions/d34b7f0b-cdd0-400e-a019-57d8be48b7ef/resourceGroups/F1_rg_central_india --json-auth`
            creds: ${{ secrets.AZURE_CREDENTIALS }}
